packages:
  - 'frontend'
peerDependencyRules:
  allowedVersions:
    tsconfck>typescript: '6'
allowBuilds:
  '@mongodb-js/zstd': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aemeath-projects/napcat@1.0.0'
  - '@aemeath-projects/napcat@1.1.0'
overrides:
  '@aemeath-projects/exostrider': link:../exostrider
  '@aemeath-projects/napcat': link:../napcat
